---
- name: OpenShift login
  shell: "oc login -u system:admin"
  become: true

- name: Disable AWS default storage class
  shell: "oc patch storageclass gp2 -p '{\"metadata\": {\"annotations\": {\"storageclass.kubernetes.io/is-default-class\": \"false\"}}}' -n openshift"
  become: true
  ignore_errors: true

- name: Disable AWS default beta storage class
  shell: "oc patch storageclass gp2 -p '{\"metadata\": {\"annotations\": {\"storageclass.beta.kubernetes.io/is-default-class\": \"false\"}}}' -n openshift"
  become: true
  ignore_errors: true

- name: Enable gluster default storage class
  shell: "oc patch storageclass glusterfs-storage -p '{\"metadata\": {\"annotations\": {\"storageclass.kubernetes.io/is-default-class\": \"true\"}}}' -n openshift"
  become: true